# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('resource_id', models.TextField(default='d4ccfbb8277111e797cf40167e98509a', max_length=32, unique=True)),
                ('platform_type', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=32)),
                ('namespace', models.TextField(max_length=32)),
                ('label', models.TextField(max_length=32)),
                ('regex', models.TextField(max_length=32)),
                ('version', models.TextField(max_length=32)),
            ],
        ),
    ]
