# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_platform', '0002_auto_20170422_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmodel',
            name='resource_id',
            field=models.TextField(default='fdd69a7c277211e797cf40167e98509a', max_length=32, unique=True),
        ),
    ]
