# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_platform', '0003_auto_20170422_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmodel',
            name='platform_type',
            field=models.TextField(default='onem2m', help_text='OneM2M, OpenHAB...', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='resource_id',
            field=models.TextField(default='a338c46c277411e797cf40167e98509a', max_length=32, unique=True),
        ),
    ]
