# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_platform', '0005_auto_20170422_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmodel',
            name='description',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='label',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='namespace',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='regex',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='resource_id',
            field=models.TextField(default='808a130c277511e797cf40167e98509a', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='version',
            field=models.TextField(max_length=32, null=True),
        ),
    ]
