# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_platform', '0008_auto_20170422_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmodel',
            name='resource_id',
            field=models.TextField(default='498c1c18277711e797cf40167e98509a', max_length=32, unique=True),
        ),
    ]
