- hosts: master
  tasks:
   - name: Deploy heapster
     shell: kubectl create -f kubernetes/kube-config/heapster/deploy/fog-kube-config/influxdb
     
   - name: Deploy mqtt
     shell: kubectl create -f kubernetes/kube-config/mosquitto_mqtt/fog

   # - name: Deploy config
   #   bash: /home/huanpc/kube-config-repo/test.config/create_configmap.sh
