- hosts: master
  tasks:   
   - name: Run master node
     shell: /home/huanpc/kube-deploy/docker-multinode/master.sh
   - name: Define master node
     shell: export MASTER_IP=192.168.30.42
   #- name: Download kubectl
   #  shell: curl -Lo /usr/local/bin/kubectl http://storage.googleapis.com/kubernetes-release/release/v1.3.6/bin/linux/amd64/kubectl && chmod +x /usr/local/bin/kubectl
   - name: Set cluster
     shell: kubectl config set-cluster fog-cluster --server=http://128.199.242.5:8080 && kubectl config set-context fog-system --cluster=fog-cluster && kubectl config use-context fog-system

- hosts: worker
  tasks:   
   - name: Define master node
     shell: export MASTER_IP=192.168.30.42
   - name: Run master node
     shell: /home/huanpc/kube-deploy/docker-multinode/worker.sh

- hosts: master
  tasks:   
   - name: Label for node
     shell: kubectl label nodes 128.199.242.5 fog-node=master && kubectl label nodes 128.199.91.17 fog-node=worker_1 && kubectl label nodes 139.59.98.138 fog-node=worker_2 && kubectl label nodes 139.59.98.157 fog-node=worker_3

- hosts: all
  tasks:
   - name: Stop firewall
     shell: ufw disable     
     

