# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('resource_id', models.TextField(auto_created=True, max_length=32, unique=True)),
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('Diode', 'Diode'), ('Semiconductor', 'Semiconductor'), ('IC', 'IC')], default='Diode', max_length=32)),
                ('description', models.CharField(choices=[('Weather-Temperature-Sensor', 'Weather Temperature'), ('Body-Temperature-Sensor', 'Body Temperature'), ('SONY-Light-Sensor-V1', 'SONY Light V1'), ('ATA-Light-Sensor-V2', 'ATA Light V2'), ('SENSYS-Atmosphere-Sensor', 'SENSYS Atmosphere')], default='Weather-Temperature-Sensor', max_length=32)),
                ('namespace', models.TextField(max_length=32, null=True)),
                ('label', models.TextField(max_length=32, null=True)),
                ('version', models.TextField(max_length=32, null=True)),
                ('manufacturer', models.TextField(default='SONY', max_length=32)),
                ('platform_listener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iot_platform.PlatformModel', to_field='resource_id')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
    ]
