# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot_platform', '0011_auto_20170422_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('resource_id', models.TextField(default='1b781b0b277811e797cf40167e98509a', max_length=32, unique=True)),
                ('sensor_type', models.TextField(default='temperature', help_text='Temperature, Light, Pressure...', max_length=32)),
                ('description', models.TextField(max_length=32, null=True)),
                ('namespace', models.TextField(max_length=32, null=True)),
                ('label', models.TextField(max_length=32, null=True)),
                ('regex', models.TextField(max_length=32, null=True)),
                ('version', models.TextField(max_length=32, null=True)),
                ('manufacturer', models.TextField(max_length=32, null=True)),
                ('platform_listener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iot_platform.PlatformModel', to_field='resource_id')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
    ]
