# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormodel',
            name='resource_id',
            field=models.TextField(auto_created=True, max_length=32, unique=True),
        ),
    ]
