apiVersion: v1
kind: ReplicationController
metadata:
    name: mqtt-2
    namespace: kube-system
spec:
    replicas: 1
    selector:
        app: mqtt-2
    template:
        metadata:
            name: mqtt-2
            labels:
                app: mqtt-2
        spec:
            containers:
            - name: mqtt-2
              image: jllopis/mosquitto:v1.4.10
              ports:
              - containerPort: 1883
              - containerPort: 9001
              volumeMounts:
              - name: mosquitto-config
                mountPath: /etc/mosquitto.d/limit_queue.conf
                subPath: limit_queue.conf
            volumes:
            - name: mosquitto-config
              configMap:
              name: mosquitto-config
              items:
              - key: limit-queue.conf
                path: limit_queue.conf
