apiVersion: v1
kind: Service
metadata:
    name: mqtt-service-2
    namespace: kube-system
spec:
    selector:
      app: mqtt-2
    ports:
        - name: mqtt
          protocol: TCP
          port: 1883
        - name: websockermqtt
          protocol: TCP
          port: 9001

